### ISSUE TITLE
 Error Loading Plugin homebridge-websocket

### ISSUE THREAD

**Issue by faruk604** [cflurin/homebridge-websocket#17]
When I start Homebridge, It says that :

 ====================
[2020-2-23 14:56:57] ERROR LOADING PLUGIN homebridge-websocket:
[2020-2-23 14:56:57] TypeError: argument fn must be a function
    at Function.wrapfunction [as function] (C:\Users\faruk\AppData\Roaming\npm\node_modules\homebridge-websocket\node_modules\depd\index.js:399:11)
    at populateConstructorExports (C:\Users\faruk\AppData\Roaming\npm\node_modules\homebridge-websocket\node_modules\http-errors\index.js:264:45)
    at Object.<anonymous> (C:\Users\faruk\AppData\Roaming\npm\node_modules\homebridge-websocket\node_modules\http-errors\index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\faruk\AppData\Roaming\npm\node_modules\homebridge-websocket\node_modules\send\index.js:15:19)

**Comment by cflurin** [comment]
Please provide following infos:

Hardware
OS and OS version
node.js version
homebridge version
homebridge-websocket version
error log
config.json
a small description
screenshots if appropriate
